version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:10.18.1
        environment:
          TERM: xterm
          EMAIL: circleci@test.test
          GIT_AUTHOR_NAME: CircleCI
          GIT_COMMITTER_NAME: CircleCI
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'ef:b4:5c:0b:93:19:ea:c8:27:92:aa:fa:b9:4e:2a:b3'
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run:
          name: Publish prerelease version
          command: TESTED_VERSION=$(npm version prerelease --preid=ci) && git push && npm publish
      - run:
          name: Run tests using published prerelease version
          command: echo "${TESTED_VERSION}" && cd test && npm install jmarceli-npm-tests@${TESTED_VERSION} && npm ls

workflows:
  tests:
    jobs:
      - run_tests
