version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:10.18.1
        environment:
          TERM: xterm
          EMAIL: circleci@test.test
          GIT_AUTHOR_NAME: CircleCI
          GIT_COMMITTER_NAME: CircleCI
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: TESTED_VERSION=$(npm version prerelease --preid=ci) && npm publish
      - run:
          command: cd test && npm i jmarceli-npm-tests@${TESTED_VERSION} && npm run test

workflows:
  tests:
    jobs:
      - run_tests
